@startuml
interface Dialogo {
    void render()
}

class DialogoWindows implements Dialogo {
    void render()
}

class DialogoMac implements Dialogo {
    void render()
}

interface FabricaDialogo {
    Dialogo crearDialogo()
}

class FabricaDialogoWindows implements FabricaDialogo {
    Dialogo crearDialogo()
}

class FabricaDialogoMac implements FabricaDialogo {
    Dialogo crearDialogo()
}

class Cliente {
    Dialogo dialogo
    Cliente(FabricaDialogo)
    void renderizarDiálogo()
}

FabricaDialogo <|-- FabricaDialogoWindows
FabricaDialogo <|-- FabricaDialogoMac
Dialogo <|-- DialogoWindows
Dialogo <|-- DialogoMac
Cliente --> FabricaDialogo
Cliente --> Dialogo
@enduml

http://www.plantuml.com/plantuml/svg/fL1BYiCm3Dtx55uc2zzW608pp6xMNQksMWJ-5DjfeP_3z2ozM1DQarfa4-ADaVJUqtlgKeQOUsS5-Onn1nhbBu4D-o0lGWxl6CZ8YDvWR5fn4q9RIAc0DkHDE2L9xc3HeSzf4VqVz0BgPF4Fjf4qrFXIwOWGtyN7JaQQSRvUjGHQfVXZQI0ZGvlNF_OAegdbMturEe_wZ_kqWFdvkYerVvPv98yggZ5JuBF2AV6K-cQArQZqkY5Ax-mJ